apiVersion: v1
kind: Service
metadata:
  name: wso2-api-manager
  labels:
    app.kubernetes.io/name: api-manager
spec:
  type: ClusterIP
  ports:
    - name: https-console
      port: 9443
      targetPort: 9443
    - name: https-gateway
      port: 8243
      targetPort: 8243
    - name: http-gateway
      port: 8280
      targetPort: 8280
  selector:
    app.kubernetes.io/name: api-manager
