apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-quickstart-dev

commonLabels:
  app: ocp-quickstart
  app.kubernetes.io/name: ocp-quickstart
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
