apiVersion: v1
kind: Service
metadata:
  name: wso2-streaming-integrator
  labels:
    app.kubernetes.io/name: streaming-integrator
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 9443
      targetPort: 9443
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: streaming-integrator
