# Kustomize overlay — QA
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wso2-qa

resources:
  - ../../base
  - namespace.yaml

labels:
  - pairs:
      environment: qa
    includeSelectors: true

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: wso2-api-manager
    newName: ghcr.io/ticxar/wso2-api-manager
    newTag: qa-latest
  - name: wso2-micro-integrator
    newName: ghcr.io/ticxar/wso2-micro-integrator
    newTag: qa-latest
  - name: wso2-identity-server
    newName: ghcr.io/ticxar/wso2-identity-server
    newTag: qa-latest
  - name: wso2-streaming-integrator
    newName: ghcr.io/ticxar/wso2-streaming-integrator
    newTag: qa-latest
